import Link from "next/link";
import ThemeToggle from "../ThemeToggle";
import HomeNavigation from "./HomeNavigation";
import TemplatePreviewFrame from "@/components/portfolio-templates/TemplatePreviewFrame";
import { createClient } from "@/lib/supabase/server";

const templates = [
  { no: "01", name: "Simple", kind: "simple", description: "A calm, editorial page that gives your work room to speak.", initials: "AM" },
  { no: "02", name: "Modern", kind: "modern", description: "A forest-green dashboard with a bold profile and project cards.", initials: "JL" },
  { no: "03", name: "Creative", kind: "creative", description: "A warm, nature-inspired collage for a more expressive story.", initials: "SK" },
];

export const dynamic = "force-dynamic";

export default async function Home() {
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getClaims();
  const signedIn = Boolean(auth?.claims?.sub);
  return (
    <main>
      <header className="site-header">
        <Link className="brand" href="#home" aria-label="EverLeaf home"><span className="brand-mark">E</span><span>EverLeaf<small>PORTFOLIO GENERATOR</small></span></Link>
        <HomeNavigation />
        <div className="header-actions"><ThemeToggle placement="header"/>{signedIn ? <><Link className="button button-quiet" href="/dashboard">My portfolios</Link><Link className="button button-primary" href="/dashboard/new">Get started <span aria-hidden="true">→</span></Link></> : <><Link className="button button-quiet" href="/login">Login</Link><Link className="button button-primary" href="/signup">Get started <span aria-hidden="true">→</span></Link></>}</div>
      </header>

      <section className="el-home-hero" id="home"><div className="el-home-hero-inner">
        <div className="el-home-hero-copy"><p className="el-home-eyebrow">❧ &nbsp; TURN YOUR SKILLS INTO OPPORTUNITIES</p><h1><span>EverLeaf</span><br/>Portfolio Generator</h1><p className="el-home-description">Create your professional portfolio with a nature-inspired design. Choose from 3 unique templates, save your information online, and showcase your work to the world.</p><div className="el-home-actions"><Link className="el-home-primary" href={signedIn ? "/dashboard/new" : "/signup"}><span aria-hidden="true">❧</span> Create Your Portfolio <span aria-hidden="true">→</span></Link><a className="el-home-secondary" href="#templates"><span aria-hidden="true">◉</span> View Templates</a></div><div className="el-home-assurance"><span>✓</span><div>Build at your own pace<small>Add your details · explore the styles · share when ready</small></div></div></div>
        <div className="el-home-art" aria-label="Floating preview of an EverLeaf Modern portfolio"><svg className="el-home-roots" viewBox="0 0 620 450" preserveAspectRatio="none" aria-hidden="true"><path d="M17 389C71 348 86 293 144 273c36-13 44-46 68-77M21 402c73-19 103-62 132-111 19-33 47-46 67-67M24 413c86 1 128-35 168-79 24-27 42-42 62-51M602 383c-59-39-77-86-126-106-37-15-44-46-67-78M602 401c-71-20-101-64-130-113-19-33-46-48-65-69M595 416c-84 1-128-38-166-81-22-26-42-42-62-50"/><path className="fine" d="M85 344c-18 17-34 27-61 35M112 317c-6-24-7-41-1-62M151 279c-18-17-31-30-41-51M191 241c-4-25-2-42 7-61M535 343c18 16 35 27 62 34M506 315c7-24 7-42 2-62M467 278c18-18 31-31 42-52M428 239c4-24 2-42-7-61"/><path className="leaves" d="M77 354c-25-5-36-19-39-38 22 1 36 13 39 38Zm34-39c-20-15-25-33-18-51 19 10 26 27 18 51Zm37-45c-24-8-34-23-33-43 22 5 34 20 33 43Zm40-41c-16-20-16-39-4-55 15 14 17 33 4 55Zm357 125c25-5 36-18 40-37-23 1-37 12-40 37Zm-33-39c20-15 25-33 18-51-19 10-27 27-18 51Zm-38-45c24-8 34-23 33-43-22 5-34 20-33 43Zm-40-41c16-20 16-39 4-55-15 14-17 33-4 55Z"/></svg><i className="el-root-light light-one"/><i className="el-root-light light-two"/><i className="el-root-light light-three"/><div className="el-floating-tablet"><div className="el-tablet-screen"><aside><div className="el-tablet-brand"><i>N</i><span>Nikenji Peñas<small>Creative Developer</small></span></div><nav><span>⌂　Home</span><span>◉　About</span><span>✳　Skills</span><span>▧　Projects</span><span>◷　Experience</span><span>✉　Contact</span></nav></aside><div className="el-tablet-content"><div className="el-tablet-topline"><span>Portfolio · Modern style</span><span>Available for work</span></div><div className="el-tablet-cover"><small>Web developer · Designer</small><strong>Hello, I’m Nikenji Peñas</strong><p>Building useful digital experiences with care.</p></div><div className="el-tablet-stats"><span><b>03</b>Featured projects</span><span><b>08</b>Core skills</span><span><b>100%</b>Curiosity</span></div><div className="el-tablet-cards"><article><b>About Me</b><p>A quick introduction, education, and experience in one clear profile.</p></article><article><b>My Skills</b><div><i>Laravel</i><i>PHP</i><i>MySQL</i><i>UI/UX</i></div></article></div></div></div></div></div>
      </div></section>

      <section className="features-band" id="features" aria-labelledby="how-title"><div className="how-heading"><h2 id="how-title">How It Works</h2><p>Create your portfolio in just a few simple steps.</p></div><div className="features"><article className="feature"><div className="feature-icon" aria-hidden="true">♙</div><h2>1. Enter Information</h2><p>Fill in your personal details, skills, education, and more.</p></article><article className="feature"><div className="feature-icon" aria-hidden="true">▤</div><h2>2. Save to Database</h2><p>Your data is securely stored online and ready when you return.</p></article><article className="feature"><div className="feature-icon" aria-hidden="true">▦</div><h2>3. Choose a Template</h2><p>Pick from three unique designs that fit your style.</p></article><article className="feature"><div className="feature-icon" aria-hidden="true">◉</div><h2>4. Generate &amp; Share</h2><p>Preview your portfolio and share it with the world.</p></article></div></section>

      <section className="templates-section" id="templates"><div className="section-heading"><p className="section-kicker">— Find your look —</p><h2>Choose Your Style</h2><p>Three ready-to-use designs. You can preview and change your selection later.</p></div><div className="template-grid">{templates.map((template) => { const key = template.kind === "simple" ? "minimal" : template.kind; return <article className={`template-card ${template.kind}`} key={template.name}><div className="template-art"><span className="template-count">{template.no}</span><TemplatePreviewFrame template={key as "minimal"|"modern"|"creative"} title={`${template.name} portfolio preview`} /></div><div className="template-info"><span className="template-kicker">TEMPLATE {template.no}</span><h3>{template.name}</h3><p>{template.description}</p><div className="template-actions"><Link href={`/template-demo/${key}`} className="template-link">Preview</Link><Link href={signedIn ? `/dashboard/new?template=${key}` : `/signup?template=${key}`} className="template-link">Use This Template <span aria-hidden="true">→</span></Link></div></div></article>; })}</div></section>

      <section className="about section-wrap" id="about"><div className="about-sign"><span className="eyebrow">ABOUT EVERLEAF</span><h2>A HOME FOR YOUR NEXT CHAPTER</h2></div><div className="about-copy"><p>Bring your profile, education, skills, projects, experience, and links together in one place.</p><p>Preview your designs, edit your details, and publish when you are ready.</p><Link className="text-link" href="/signup">Start your portfolio <span aria-hidden="true">→</span></Link></div></section>

      <section className="contact section-wrap" id="contact"><div className="contact-intro"><span className="eyebrow">YOUR NEXT STEP</span><h2>Let your work take root.</h2><p>Questions about EverLeaf? Reach Nikenji through email, phone, Facebook, or Messenger.</p></div><div className="contact-details"><a className="contact-link" href="mailto:penasnekenji2007@gmail.com"><span aria-hidden="true">✉</span>Email Nikenji</a><a className="contact-link" href="tel:+639187943762"><span aria-hidden="true">☎</span>0918 794 3762</a><a className="contact-link" href="https://www.facebook.com/search/top?q=NIKENJI%20PENAS" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">f</span>Find NIKENJI PENAS on Facebook</a><a className="contact-link" href="https://www.messenger.com/new" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">◉</span>Open Messenger</a><p>Facebook and Messenger open in a new tab. Search for NIKENJI PENAS in Messenger to start a chat.</p></div><Link className="button button-primary button-large contact-cta" href="/signup">Start your journey <span aria-hidden="true">→</span></Link></section>
      <footer className="site-footer section-wrap"><Link className="brand" href="#home"><span className="brand-mark">E</span><span>EverLeaf<small>PORTFOLIO GENERATOR</small></span></Link><span>EverLeaf Portfolio Generator · Grow your story. Share your work.</span><a className="back-to-top" href="#home" aria-label="Back to top"><span aria-hidden="true">↑</span><span>Back to top</span></a></footer>
    </main>
  );
}
