<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#102016">
    <title>My portfolios · EverLeaf Portfolio Generator</title>
    <style>
        :root{color-scheme:dark;--forest:#102016;--deep:#09140e;--leaf:#bdd28c;--cream:#f4f0dc;--soft:#cbd4c2;--line:#dce8cb2c;--glass:#0e1c13eF;--muted:#abb8a5}
        *{box-sizing:border-box}body{min-height:100vh;margin:0;background:#0a160e url('{{ asset('images/forest-hero.svg') }}') center/cover fixed no-repeat;color:var(--cream);font:14px/1.5 Inter,"Segoe UI",Arial,sans-serif}body:before{position:fixed;z-index:-1;inset:0;background:linear-gradient(90deg,#08140ee8,#0a170fd9 45%,#08140ee8),linear-gradient(0deg,#08120ce8,#08120c66);content:""}a{color:inherit}
        .app-shell{display:grid;grid-template-columns:205px minmax(0,1fr);min-height:100vh;max-width:1600px;margin:auto}.sidebar{position:sticky;top:0;display:flex;height:100vh;flex-direction:column;padding:21px 14px;border-right:1px solid var(--line);background:#0b1911da;backdrop-filter:blur(14px)}.brand{display:flex;align-items:center;gap:9px;padding:0 7px 22px;border-bottom:1px solid var(--line);font:700 18px Georgia,"Times New Roman",serif;text-decoration:none}.brand-mark{display:grid;place-items:center;width:31px;height:31px;border:1px solid #d4e5b264;border-radius:50% 50% 50% 12px;background:linear-gradient(145deg,#a9c77b,#436743);color:#132016;font-size:20px}.side-nav{display:grid;gap:5px;padding-top:18px}.side-nav a{display:flex;align-items:center;gap:10px;padding:10px 11px;border:1px solid transparent;border-radius:9px;color:#c6d0bf;text-decoration:none;font-size:12px;font-weight:600;transition:background .15s,border-color .15s}.side-nav a:hover,.side-nav a.active{border-color:#c9dda233;background:#dce9c818;color:#edf2dd}.side-nav a.active{box-shadow:inset 2px 0 #bad18c}.side-icon{display:grid;width:17px;place-items:center;color:#c6d99a;font-size:15px}.side-bottom{margin-top:auto;padding:15px 6px 2px;border-top:1px solid var(--line)}.side-user{display:flex;align-items:center;gap:9px;color:#e4e8d9;font-size:11px}.user-avatar{display:grid;place-items:center;width:30px;height:30px;border:1px solid #d2e0b760;border-radius:50%;background:linear-gradient(145deg,#809963,#314b30);color:#f6f2df;font-weight:800}.side-user small{display:block;color:#9eae9b;font-size:9px}
        .workspace{min-width:0}.topbar{display:flex;align-items:center;justify-content:flex-end;gap:12px;min-height:66px;padding:11px clamp(18px,4vw,54px);border-bottom:1px solid var(--line);background:#0d1a12a8;backdrop-filter:blur(12px)}.topbar-user{display:flex;align-items:center;gap:9px;color:#d2dacb;font-size:12px}.topbar .user-avatar{width:31px;height:31px}.signout{border:1px solid #dce8cb42;border-radius:9px;padding:7px 11px;background:#101f15;color:#eff0dc;font:inherit;font-size:11px;cursor:pointer}.signout:hover{background:#20341f}
        main{width:min(1050px,100%);margin:0 auto;padding:42px clamp(18px,4vw,52px) 60px}.heading{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:24px}.eyebrow{display:inline-flex;align-items:center;gap:7px;margin:0 0 8px;color:#c8dc9b;font-size:10px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.heading h1{margin:0 0 5px;font:600 clamp(31px,4vw,40px)/1.1 Georgia,"Times New Roman",serif;letter-spacing:-.03em}.heading p{margin:0;color:#c0cbbb;font-size:12px}.button{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:39px;border:1px solid #dce9b65e;border-radius:10px;padding:9px 13px;background:linear-gradient(120deg,#829e58,#4d713e);color:#f4f1de;text-decoration:none;font-size:11px;font-weight:750;box-shadow:0 5px 17px #0004;transition:transform .15s,filter .15s}.button:hover{transform:translateY(-1px);filter:brightness(1.1)}.notice{margin:0 0 15px;padding:10px 13px;border:1px solid #bfd58a72;border-radius:10px;background:#33482b;color:#eef3d8;font-size:12px}
        .list{display:grid;gap:11px}.portfolio{display:grid;grid-template-columns:142px minmax(0,1fr) auto;align-items:center;gap:17px;padding:12px;border:1px solid #dce8cb36;border-radius:13px;background:linear-gradient(110deg,#10251adf,#0c1c13eF);box-shadow:0 9px 24px #0004;transition:border-color .16s,transform .16s}.portfolio:hover{transform:translateY(-1px);border-color:#c5dc9178}.portfolio-thumb{position:relative;display:grid;place-items:center;height:108px;overflow:hidden;border:1px solid #d7e6c784;border-radius:8px;background:linear-gradient(0deg,#10221571,#10221520),url('{{ asset('images/forest-hero.svg') }}') center 63%/cover}.portfolio-thumb:before{position:absolute;inset:0;background:linear-gradient(90deg,#08150b78,#14271820);content:""}.portfolio-thumb.thumb-modern{background-position:68% 53%}.portfolio-thumb.thumb-creative{background-position:35% 55%;filter:saturate(1.15)}.portfolio-thumb img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.thumb-initial{position:relative;display:grid;place-items:center;width:41px;height:41px;border:1px solid #e3edcfab;border-radius:50%;background:#263c29aa;color:#f1f2dd;font:700 19px Georgia,serif;box-shadow:0 3px 14px #0008}.thumb-caption{position:absolute;right:6px;bottom:5px;left:6px;overflow:hidden;color:#f5f1df;font:600 8px Georgia,serif;text-overflow:ellipsis;white-space:nowrap;text-shadow:0 1px 4px #000}
        .portfolio-main{display:flex;min-width:0;align-items:flex-start;gap:12px}.avatar{display:grid;flex:none;place-items:center;width:34px;height:34px;border:1px solid #cfe0a86a;border-radius:50%;background:linear-gradient(145deg,#829963,#314b30);color:#f5f1df;font-size:13px;font-weight:800}.portfolio-details{min-width:0}.name{overflow-wrap:anywhere;color:#f3f0df;font:600 16px/1.25 Georgia,"Times New Roman",serif}.meta{margin-top:4px;color:#bbc8b5;font-size:10px}.preview-links{display:flex;align-items:center;flex-wrap:wrap;gap:6px 11px;margin-top:8px;color:#aebba8;font-size:10px}.preview-links a{color:#d3e4a9;text-decoration:none;font-weight:650}.preview-links a:hover{text-decoration:underline}.status{display:inline-flex;align-items:center;gap:5px;border:1px solid #d7dfc630;border-radius:999px;padding:2px 7px;background:#5a2925a3;color:#ffd6ca;font-size:9px;font-weight:750}.status.is-published{border-color:#aac67853;background:#354b2ba8;color:#e2efbf}.public-url{flex:1 0 100%;max-width:100%;overflow-wrap:anywhere;color:#aebc9c;font-size:9px}.actions{display:flex;align-items:center;justify-content:flex-end;gap:6px;flex-wrap:wrap}.actions form{margin:0}.view-button,.edit-button,.delete,.publish{display:inline-flex;align-items:center;justify-content:center;gap:5px;min-height:32px;border:1px solid #d7e4be4c;border-radius:8px;padding:6px 9px;background:#283f28;color:#f0efd9;text-decoration:none;font:inherit;font-size:10px;font-weight:700;cursor:pointer}.view-button:hover,.publish:hover{background:#3c5b34}.edit-button{background:#17291d}.edit-button:hover{background:#263c2b}.delete{border-color:#d1947963;background:#422d25;color:#ffe0d0}.delete:hover{background:#60362b}.publish{border-color:#d5e7a66a;background:#536e3c}
        .empty{padding:48px 22px;text-align:center;border:1px solid #dce8cb3d;border-radius:15px;background:#102218df;box-shadow:0 12px 32px #0004}.empty-mark{display:grid;place-items:center;width:51px;height:51px;margin:0 auto 12px;border:1px solid #d6e5ae52;border-radius:50%;background:#283d28;color:#d6e7a9;font-size:23px}.empty strong{display:block;margin-bottom:5px;color:#f2f0dd;font:600 19px Georgia,serif}.empty p{max-width:350px;margin:0 auto 17px;color:#c1cbb9;font-size:12px}
        body{background:linear-gradient(90deg,rgba(5,18,11,.72),rgba(7,19,12,.55) 48%,rgba(5,18,11,.67)),linear-gradient(0deg,rgba(4,13,8,.69),rgba(4,13,8,.10)),url('https://images.unsplash.com/photo-1774793846873-d922ef2733b1?auto=format&fit=crop&w=2200&q=80') center 58%/cover fixed no-repeat}body:before{display:none}.portfolio-thumb{background-image:linear-gradient(0deg,#10221571,#10221520),url('https://images.unsplash.com/photo-1774793846873-d922ef2733b1?auto=format&fit=crop&w=900&q=78');background-position:center 58%;background-size:cover}.portfolio-thumb.thumb-modern{background-position:center 53%}.portfolio-thumb.thumb-creative{background-position:center 62%;filter:saturate(1.08)}
        @media(max-width:900px){.app-shell{grid-template-columns:174px minmax(0,1fr)}.sidebar{padding-inline:10px}.portfolio{grid-template-columns:112px minmax(0,1fr);gap:12px}.portfolio-thumb{height:95px}.actions{grid-column:2;justify-content:flex-start}.portfolio-main{grid-column:2;grid-row:1}.portfolio-thumb{grid-column:1;grid-row:1/3}.portfolio{align-items:start}}
        @media(max-width:620px){.app-shell{display:block}.sidebar{position:relative;width:100%;height:auto;padding:10px 14px;border-right:0;border-bottom:1px solid var(--line)}.brand{padding:0 3px 9px;border:0}.side-nav{display:flex;gap:4px;overflow-x:auto;padding:2px 0 0}.side-nav a{flex:none;gap:6px;padding:7px 8px;font-size:10px}.side-icon{font-size:13px}.side-bottom{display:none}.topbar{min-height:49px;padding:7px 15px}.topbar-user{font-size:10px}main{padding:27px 14px 43px}.heading{align-items:flex-start;flex-direction:column;gap:13px;margin-bottom:17px}.heading .button{align-self:stretch}.portfolio{grid-template-columns:82px minmax(0,1fr);gap:10px;padding:9px}.portfolio-thumb{height:82px}.portfolio-main{gap:8px}.avatar{width:28px;height:28px;font-size:11px}.name{font-size:14px}.meta{font-size:9px}.preview-links{gap:5px 8px;font-size:9px}.actions{grid-column:1/-1;justify-content:flex-end;padding-top:8px;border-top:1px solid var(--line)}.view-button,.edit-button,.delete,.publish{min-height:31px;padding:5px 8px;font-size:9px}.public-url{font-size:8px}}
        @media(max-width:370px){.side-nav a{padding:6px;font-size:9px}.side-nav{gap:1px}.portfolio{grid-template-columns:69px minmax(0,1fr)}.portfolio-thumb{height:75px}.actions{justify-content:space-between}}
        @media(prefers-reduced-motion:reduce){.button,.portfolio{transition:none}}
        .view-button,.edit-button,.delete,.publish,.signout{min-height:40px;padding:8px 11px;font-size:11px;transition:background .15s,border-color .15s,transform .15s,filter .15s}
        .view-button:hover,.edit-button:hover,.delete:hover,.publish:hover,.signout:hover{transform:translateY(-1px);filter:brightness(1.12)}
        a:focus-visible,button:focus-visible{outline:3px solid #e0eeae;outline-offset:3px}
        .recovery{margin-top:34px}.recovery-heading{margin-bottom:11px}.recovery-heading h2{margin:0;color:var(--cream);font:600 22px Georgia,"Times New Roman",serif}.recovery-heading p{margin:4px 0 0;color:var(--soft);font-size:12px}.recovery-list{display:grid;gap:8px}.recovery-item{grid-template-columns:minmax(0,1fr) auto;padding:12px 15px;background:linear-gradient(110deg,#17241add,#102018e8)}.recovery-item .portfolio-main{align-items:center}.recovery-item .meta{font-size:11px}.restore-button{min-height:40px;border:1px solid #d7e7a77a;border-radius:9px;padding:8px 13px;background:linear-gradient(120deg,#829e58,#4d713e);color:#f4f1de;font:inherit;font-size:12px;font-weight:750;cursor:pointer;transition:transform .16s,filter .16s,box-shadow .16s}.restore-button:hover{transform:translateY(-2px) scale(1.03);filter:brightness(1.12);box-shadow:0 0 17px #95ca6b70}.recovery-item form{margin:0}
        .recovery-empty{padding:16px;border:1px solid var(--line);border-radius:11px;background:#102218bd;color:var(--soft);font-size:12px}
    </style>
    <link rel="stylesheet" href="{{ asset('css/everleaf-cursors.css') }}">
    <link rel="stylesheet" href="{{ asset('css/everleaf-theme-toggle.css') }}">
    <script src="{{ asset('js/everleaf-theme-toggle.js') }}" defer></script>
</head>
<body>
<div class="app-shell">
    <aside class="sidebar">
        <a class="brand" href="{{ route('home') }}"><span class="brand-mark" aria-hidden="true">E</span> EverLeaf</a>
        <nav class="side-nav" aria-label="Portfolio navigation">
            <a href="{{ route('home') }}"><span class="side-icon" aria-hidden="true">⌂</span> Home</a>
            <a class="active" href="{{ route('portfolios.index') }}" aria-current="page"><span class="side-icon" aria-hidden="true">▣</span> My Portfolio</a>
            <a href="{{ route('portfolios.create') }}"><span class="side-icon" aria-hidden="true">＋</span> Create New</a>
            <a href="{{ $portfolios->isNotEmpty() ? route('portfolios.templates', $portfolios->first()) : route('home').'#templates' }}"><span class="side-icon" aria-hidden="true">▦</span> Templates</a>
        </nav>
        <div class="side-bottom"><div class="side-user"><span class="user-avatar" aria-hidden="true">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</span><span>{{ auth()->user()->name }}<small>Portfolio workspace</small></span></div></div>
    </aside>
    <div class="workspace">
        <header class="topbar"><div class="topbar-user"><span class="user-avatar" aria-hidden="true">{{ strtoupper(substr(auth()->user()->name, 0, 1)) }}</span>{{ auth()->user()->name }}</div><form method="POST" action="{{ route('logout') }}">@csrf<button class="signout" type="submit">Sign out</button></form></header>
        <main>
            <div class="heading"><div><div class="eyebrow">❧ &nbsp; Your creative workspace</div><h1>My Portfolio</h1><p>Manage your saved portfolios. View, edit, or delete anytime.</p></div><a class="button" href="{{ route('portfolios.create') }}"><span aria-hidden="true">＋</span> Create New Portfolio</a></div>
            @if (session('success'))<div class="notice" role="status">{{ session('success') }}</div>@endif
            @if ($portfolios->isEmpty())
                <div class="empty"><div class="empty-mark" aria-hidden="true">❧</div><strong>Your first portfolio starts here</strong><p>Add your experience, projects, and skills. Choose a style and publish when you’re ready.</p><a class="button" href="{{ route('portfolios.create') }}">Create your portfolio</a></div>
            @else
                <div class="list">
                    @foreach ($portfolios as $portfolio)
                        @php($templateLabel = $portfolio->template_key === 'minimal' ? 'Simple' : ucfirst($portfolio->template_key))
                        <article class="portfolio">
                            <div class="portfolio-thumb thumb-{{ $portfolio->template_key }}">
                                @if ($portfolio->profile_photo_path)<img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($portfolio->profile_photo_path) }}" alt="Profile photo of {{ $portfolio->full_name }}">@else<span class="thumb-initial" aria-hidden="true">{{ strtoupper(substr($portfolio->full_name, 0, 1)) }}</span>@endif
                                <span class="thumb-caption">{{ $portfolio->full_name }} · {{ $templateLabel }}</span>
                            </div>
                            <div class="portfolio-main"><div class="avatar" aria-hidden="true">{{ strtoupper(substr($portfolio->full_name, 0, 1)) }}</div><div class="portfolio-details">
                                <div class="name">{{ $portfolio->full_name }}</div><div class="meta">Template · {{ $templateLabel }} <span aria-hidden="true">·</span> Created {{ $portfolio->created_at->format('M j, Y') }}</div>
                                <div class="preview-links"><span class="status {{ $portfolio->is_published ? 'is-published' : '' }}">● {{ $portfolio->is_published ? 'Published' : 'Private' }}</span><a href="{{ route('portfolios.templates', $portfolio) }}">Choose from 3 designs</a>@if ($portfolio->is_published)<a href="{{ route('portfolios.public', $portfolio->slug) }}" target="_blank" rel="noopener noreferrer">Open public page</a><span class="public-url">{{ route('portfolios.public', $portfolio->slug) }}</span>@endif</div>
                            </div></div>
                            <div class="actions">
                                <a class="view-button" href="{{ route('portfolios.preview', ['portfolio' => $portfolio, 'template' => $portfolio->template_key]) }}">◉ View</a>
                                <a class="edit-button" href="{{ route('portfolios.edit', $portfolio) }}">✎ Edit</a>
                                <form method="POST" action="{{ route('portfolios.publish', $portfolio) }}" @unless($portfolio->is_published) onsubmit="return confirm('Publishing makes this portfolio page and its listed contact details visible to anyone with the link. Continue?')" @endunless>@csrf<button class="publish" type="submit">{{ $portfolio->is_published ? 'Make private' : 'Publish' }}</button></form>
                                <form method="POST" action="{{ route('portfolios.destroy', $portfolio) }}" onsubmit="return confirm('Delete this portfolio and its saved sections?')">@csrf @method('DELETE')<button class="delete" type="submit">Delete</button></form>
                            </div>
                        </article>
                    @endforeach
                </div>
            @endif
            <section class="recovery" aria-labelledby="recovery-title">
                <div class="recovery-heading"><h2 id="recovery-title">Recently deleted</h2><p>Deleted portfolios stay here with their saved information, images, and design, ready to restore.</p></div>
                @if ($deletedPortfolios->isNotEmpty())
                    <div class="recovery-list">
                        @foreach ($deletedPortfolios as $deletedPortfolio)
                            <article class="portfolio recovery-item">
                                <div class="portfolio-main"><div class="avatar" aria-hidden="true">{{ strtoupper(substr($deletedPortfolio->full_name, 0, 1)) }}</div><div class="portfolio-details"><div class="name">{{ $deletedPortfolio->full_name }}</div><div class="meta">{{ $deletedPortfolio->template_key === 'minimal' ? 'Simple' : ucfirst($deletedPortfolio->template_key) }} design · Deleted {{ $deletedPortfolio->deleted_at->format('M j, Y') }}</div></div></div>
                                <form method="POST" action="{{ route('portfolios.restore', $deletedPortfolio->id) }}" onsubmit="return confirm('Restore this portfolio with all its saved information and design?')">@csrf<button class="restore-button" type="submit">↶ Restore portfolio</button></form>
                            </article>
                        @endforeach
                    </div>
                @else
                    <div class="recovery-empty">Nothing to recover right now. Portfolios you delete will appear here.</div>
                @endif
            </section>
        </main>
    </div>
</div>
</body>
</html>
