<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ece5d0">
    <title>{{ $portfolio->full_name }} · Creative Portfolio</title>
    <style>
        .embedded-preview{width:1200px;min-width:1200px;overflow:hidden;scrollbar-width:none}.embedded-preview::-webkit-scrollbar{display:none}.demo-preview main a{pointer-events:none}
        :root{color-scheme:light;--paper:#eee7d4;--sheet:#f5f0e1;--ink:#243027;--muted:#66705e;--moss:#50684a;--line:#cfc5a8;--leaf:#738c5b}*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:24px}body{margin:0;background:radial-gradient(ellipse at 0 0,#d3d5b6 0,transparent 19%),radial-gradient(ellipse at 100% 13%,#d9d7b7 0,transparent 21%),radial-gradient(ellipse at 93% 100%,#c9d0b2 0,transparent 23%),radial-gradient(ellipse at 5% 100%,#d1d1b4 0,transparent 19%),repeating-linear-gradient(0deg,#efe9d9 0 5px,#ece5d2 6px 7px);color:var(--ink);font:14px/1.6 "Trebuchet MS",Segoe UI,Arial,sans-serif}.toolbar{position:sticky;top:0;z-index:10;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px max(20px,calc((100vw - 1160px)/2));border-bottom:1px solid #d2c8ad;background:#eee8d8eF;backdrop-filter:blur(12px)}.toolbar a{color:#536b4e;text-decoration:none;font-size:12px;font-weight:700}.toolbar .preview-label{color:#727964;font-size:12px}.toolbar button{border:0;border-radius:999px;padding:8px 13px;background:#5e774c;color:#fffbea;font:inherit;font-size:11px;font-weight:750;cursor:pointer}.template-notice{max-width:1120px;margin:12px auto 0;padding:10px 13px;border:1px solid #bac89e;border-radius:9px;background:#eff2e2;color:#435e43;font-size:12px}
        .wrap{position:relative;max-width:1160px;margin:27px auto 56px;padding:0 20px}.wrap:before,.wrap:after{position:absolute;z-index:2;width:94px;height:145px;background:url('{{ asset('images/login-foliage.svg') }}') center/contain no-repeat;content:"";opacity:.42;pointer-events:none}.wrap:before{top:38px;left:-5px;transform:rotate(-14deg)}.wrap:after{right:-5px;bottom:17px;transform:scaleX(-1) rotate(-14deg)}.paper{position:relative;overflow:hidden;padding:18px;border:1px solid #bcb194;border-radius:14px;background:linear-gradient(145deg,#f5f0e2ed,#eae3cfeb),url('{{ asset('images/forest-hero.svg') }}') center/cover;box-shadow:0 20px 55px #27301e29}.paper:before{position:absolute;inset:6px;border:1px solid #e4dcc8;border-radius:10px;content:"";pointer-events:none}.top-nav{position:relative;z-index:1;display:flex;justify-content:flex-end;gap:19px;padding:4px 11px 10px;border-bottom:1px solid #cfc5ac}.top-nav a{color:#53614c;text-decoration:none;font-size:10px;font-weight:700}.top-nav a:hover{text-decoration:underline;text-underline-offset:3px}.hero{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:13px}.profile-panel,.about-panel,.section{position:relative;overflow:hidden;border:1px solid #d1c6a9;border-radius:17px;background:linear-gradient(135deg,#f8f4e9ed,#eee7d3f2);box-shadow:0 4px 14px #51462d0d}.profile-panel{min-height:190px;padding:19px}.profile-main{display:grid;grid-template-columns:78px minmax(0,1fr);align-items:center;gap:13px}.portrait{width:76px;height:76px;object-fit:cover;border:2px solid #768663;border-radius:50%;box-shadow:0 3px 12px #25391f3d}.initials{display:grid;place-items:center;background:linear-gradient(145deg,#c4cba9,#758762);color:#293829;font:700 29px Georgia,serif}.profile-panel h1{margin:0;color:#243127;font:600 clamp(22px,3vw,32px)/1.1 Georgia,"Times New Roman",serif;letter-spacing:-.025em}.role{margin:3px 0 0;color:#69715e;font-size:10px}.quote{margin:12px 0 0 88px;color:#59694c;font:italic 13px/1.4 Georgia,serif}.about-panel{min-height:190px;padding:20px 19px}.section h2,.about-panel h2{display:flex;align-items:center;gap:7px;margin:0 0 10px;color:#465a40;font:700 15px Georgia,"Times New Roman",serif}.section h2:before,.about-panel h2:before{color:#738d59;content:"❧"}.about-panel p{margin:0;color:#535c4e;font-size:11px;line-height:1.7}.about-photo{position:absolute;right:10px;bottom:-2px;width:66px;height:76px;object-fit:cover;border:4px solid #f4eedf;border-radius:4px;box-shadow:0 3px 12px #202d1d2b;transform:rotate(5deg)}
        .collage{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.section{padding:15px 16px;scroll-margin-top:22px}.section.skills{align-self:start}.skill-list{display:flex;flex-wrap:wrap;gap:6px}.skill{display:inline-flex;align-items:center;gap:5px;padding:5px 9px;border:1px solid #cbd0b5;border-radius:999px;background:#e9ead8;color:#40533e;font-size:10px;font-weight:700}.skill:before{color:#637d4e;content:"❧"}.education-list,.experience-list{display:grid;gap:10px}.timeline-item{position:relative;padding-left:12px;border-left:2px solid #9ca77b}.timeline-item:before{position:absolute;top:3px;left:-5px;width:7px;height:7px;border-radius:50%;background:#708557;content:""}.timeline-item h3{margin:0;color:#334031;font-size:11px}.meta{margin:2px 0;color:#737a66;font-size:9px}.timeline-item p{margin:3px 0 0;color:#596051;font-size:9px;line-height:1.5}
        .projects{grid-column:1}.project-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.project{overflow:hidden;border:1px solid #d7cfb8;border-radius:10px;background:#e9e5d5}.project-media{height:90px;overflow:hidden;background:linear-gradient(145deg,#8c9a70,#3e6244)}.project-media img{width:100%;height:100%;object-fit:cover}.project-body{padding:9px}.project h3{margin:0;color:#303a2d;font:600 12px Georgia,serif}.project p{margin:4px 0 0;color:#606556;font-size:9px;line-height:1.45}.tags{margin-top:5px;color:#728064;font-size:8px}.project-links{display:flex;gap:9px;margin-top:5px}.project-links a{color:#4f6947;text-decoration:none;font-size:9px;font-weight:700}.experience{grid-column:2}.education{grid-column:2}.contact{grid-column:1/-1}.contact-row{display:flex;flex-wrap:wrap;gap:8px 16px;overflow-wrap:anywhere}.contact-row a,.contact-row span{color:#4d6247;text-decoration:none;font-size:10px}.contact-row a:hover{text-decoration:underline}.social-list{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.social-list a{display:inline-flex;align-items:center;gap:4px;padding:5px 9px;border:1px solid #cbd1b5;border-radius:999px;background:#edf0e1;color:#496147;text-decoration:none;font-size:9px;font-weight:700}.social-list a:hover{background:#dfe6d0}.footer{position:relative;z-index:1;padding:13px 0 2px;color:#707765;text-align:center;font-size:9px}
        .empty-state{margin:0;padding:10px;border:1px dashed #bdc5a7;border-radius:9px;color:#68725c;font-size:10px}
        body{background:linear-gradient(rgba(8,19,12,.52),rgba(8,19,12,.62)),url('https://images.unsplash.com/photo-1546835196-5fe79a546d7c?auto=format&fit=crop&w=2000&q=78') center/cover fixed}.paper{background:linear-gradient(145deg,rgba(245,240,226,.89),rgba(234,227,207,.91)),url('https://images.unsplash.com/photo-1546835196-5fe79a546d7c?auto=format&fit=crop&w=1400&q=76') center/cover}
        @media(max-width:720px){.toolbar{padding:9px 12px}.toolbar .preview-label{display:none}.wrap{margin:16px auto 35px;padding:0 11px}.wrap:before,.wrap:after{width:62px;height:100px}.paper{padding:12px}.top-nav{gap:11px;padding-right:4px}.top-nav a{font-size:9px}.hero{grid-template-columns:1fr}.profile-panel,.about-panel{min-height:0;padding:15px}.collage{grid-template-columns:1fr;gap:10px;margin-top:10px}.projects,.experience,.education,.contact{grid-column:1}.projects{grid-row:auto}.project-media{height:120px}.about-photo{width:52px;height:58px}}
        @media(max-width:420px){.profile-main{grid-template-columns:60px minmax(0,1fr);gap:10px}.portrait{width:58px;height:58px}.profile-panel h1{font-size:22px}.quote{margin-left:70px}.top-nav{justify-content:center;gap:9px}.top-nav a{font-size:8px}.section{padding:13px}.project-grid{grid-template-columns:1fr 1fr}.project-media{height:82px}}
        /* Reference-led parchment and woodland layout for the Creative portfolio. */
        body{background:linear-gradient(rgba(6,18,11,.48),rgba(6,18,11,.62)),url('https://images.unsplash.com/photo-1774793846873-d922ef2733b1?auto=format&fit=crop&w=2200&q=80') center/cover fixed;color:var(--ink)}
        .wrap{max-width:1240px;margin:28px auto 58px;padding:0 24px}
        .wrap:before,.wrap:after{z-index:2;width:105px;height:155px;opacity:.55;filter:drop-shadow(0 5px 7px #15220f55)}
        .paper{padding:18px 22px 14px;border:1px solid #b9aa83;border-radius:13px;background:linear-gradient(145deg,rgba(247,241,222,.92),rgba(232,222,194,.94)),url('https://images.unsplash.com/photo-1774793846873-d922ef2733b1?auto=format&fit=crop&w=1500&q=74') center/cover;box-shadow:0 24px 70px #0008}
        .paper:before{inset:7px;border-color:#fff8e7;border-radius:9px}
        .top-nav{justify-content:center;gap:clamp(12px,2.7vw,31px);margin:-2px -2px 0;padding:10px 14px;border:1px solid #6d80544c;border-radius:999px;background:linear-gradient(115deg,#314c32,#1c3829);box-shadow:0 7px 18px #26371f35}
        .top-nav a{color:#f1efdc;font-size:11px;text-shadow:0 1px 2px #0006}.top-nav a:hover{color:#d6e6ad;text-decoration:none}
        .hero{grid-template-columns:1fr 1fr;align-items:center;gap:24px;margin-top:16px;padding:16px 14px 19px;border-bottom:1px solid #b9aa83a8}
        .profile-panel,.about-panel,.section{border:1px solid #d0c39f;border-radius:20px;background:linear-gradient(145deg,rgba(250,246,231,.82),rgba(240,232,211,.76));box-shadow:0 8px 22px #4c492d12}
        .profile-panel{min-height:192px;padding:17px;border-color:transparent;background:transparent;box-shadow:none}
        .profile-main{grid-template-columns:88px minmax(0,1fr);gap:14px}.portrait{width:84px;height:84px;border:3px solid #e9dfc5;box-shadow:0 0 0 2px #6e8059,0 7px 18px #1723183d}.profile-panel h1{font-size:clamp(23px,3vw,34px)}.role{font-size:11px}.quote{margin:12px 0 0 103px;color:#56613f;font-size:15px}
        .about-panel{display:grid;grid-template-columns:minmax(0,1fr) 112px;align-items:center;gap:14px;min-height:170px;padding:17px}.section h2,.about-panel h2{margin-bottom:9px;color:#3f583c;font-size:17px}.about-panel p{font-size:11px;line-height:1.65}.about-photo{position:static;width:112px;height:120px;border:5px solid #f5efd9;border-radius:8px;box-shadow:0 7px 18px #3e432c44;transform:rotate(2deg)}.forest-photo{background:linear-gradient(#07180d22,#07180d22),url('https://images.unsplash.com/photo-1774793846873-d922ef2733b1?auto=format&fit=crop&w=650&q=75') center/cover}
        .collage{grid-template-columns:1fr 1fr;gap:14px;margin-top:15px;padding:0 7px}.section{min-height:160px;padding:17px 18px;scroll-margin-top:22px}.section.skills{align-self:stretch}.skill-list{gap:8px}.skill{padding:6px 10px;border-color:#bac7a0;border-radius:999px;background:#e6e8d3;color:#3e5439;font-size:10px}.skill:before{font-size:12px}
        .education-list,.experience-list{gap:12px}.timeline-item{padding:2px 0 3px 14px;border-color:#89976a}.timeline-item h3{font-size:12px}.meta{font-size:10px}.timeline-item p{font-size:10px;line-height:1.55}
        .projects{grid-column:1}.project-grid{gap:11px}.project{border-color:#d1c5a8;border-radius:12px;background:#f5efdf;box-shadow:0 4px 12px #4f4b3214}.project-media{height:105px;background:linear-gradient(145deg,#8c9a70,#3e6244)}.project-placeholder{background:linear-gradient(0deg,#10221524,#10221508),url('https://images.unsplash.com/photo-1774793846873-d922ef2733b1?auto=format&fit=crop&w=700&q=74') center/cover}.project-body{padding:10px}.project h3{font-size:13px}.project p{font-size:10px;line-height:1.5}.tags{font-size:9px}.project-links a{font-size:10px}
        .experience{grid-column:2}.education{grid-column:2}.contact{grid-column:1/-1;min-height:0;background:linear-gradient(115deg,rgba(243,237,218,.84),rgba(237,229,207,.78))}.contact-row{gap:9px 19px}.contact-row a,.contact-row span{font-size:11px}.social-list{gap:8px}.social-list a{min-width:33px;min-height:33px;justify-content:center;border-color:#bac6a1;background:#e8ead8;color:#40563b;font-size:10px}.social-list a:hover{background:#d9e3c6}.empty-state{padding:12px;border-color:#aab994;border-radius:11px;background:#edf0df99;font-size:10px}.footer{padding:16px 0 3px;color:#647158;font-size:10px}
        @media(max-width:720px){.wrap{margin:16px auto 36px;padding:0 11px}.paper{padding:12px}.top-nav{gap:9px;padding:9px 8px;border-radius:13px;flex-wrap:wrap}.top-nav a{font-size:9px}.hero{grid-template-columns:1fr;gap:10px;margin-top:10px;padding:9px 4px 14px}.profile-panel{min-height:0;padding:12px}.about-panel{min-height:0;grid-template-columns:minmax(0,1fr) 82px;padding:13px}.about-photo{width:82px;height:96px}.collage{grid-template-columns:1fr;gap:10px;margin-top:10px;padding:0 2px}.projects,.experience,.education,.contact{grid-column:1}.project-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.project-media{height:115px}}
        @media(max-width:420px){.profile-main{grid-template-columns:62px minmax(0,1fr);gap:10px}.portrait{width:60px;height:60px}.profile-panel h1{font-size:22px}.quote{margin-left:72px}.about-panel{grid-template-columns:minmax(0,1fr) 70px;gap:8px}.about-photo{width:70px;height:84px}.section{padding:13px}.project-grid{grid-template-columns:1fr 1fr}.project-media{height:84px}.project-body{padding:8px}}
        @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
    </style>
    <link rel="stylesheet" href="{{ asset('css/everleaf-cursors.css') }}">
    <link rel="stylesheet" href="{{ asset('css/everleaf-theme-toggle.css') }}">
    <link rel="stylesheet" href="{{ asset('css/portfolio-navigation.css') }}">
    <link rel="stylesheet" href="{{ asset('css/creative-portfolio.css') }}">
    <script src="{{ asset('js/everleaf-theme-toggle.js') }}" defer></script>
    <script src="{{ asset('js/portfolio-section-navigation.js') }}" defer></script>
</head>
<body class="site-template-creative {{ ($embedded ?? false) ? 'embedded-preview' : '' }} {{ ($demo ?? false) ? 'demo-preview' : '' }}">
@include('portfolios.templates._toolbar')
<main class="wrap"><div class="paper">
    <nav class="top-nav portfolio-section-nav" aria-label="Portfolio sections"><a href="#home">Home</a><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#education">Education</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav>
    <section class="hero" id="home">
        <div class="profile-panel"><div class="profile-main">@if($portfolio->profile_photo_path)<img class="portrait" src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($portfolio->profile_photo_path) }}" alt="Profile photo of {{ $portfolio->full_name }}">@else<div class="portrait initials" aria-hidden="true">{{ strtoupper(substr($portfolio->full_name, 0, 1)) }}</div>@endif<div><p class="role">Portfolio · Creative style</p><h1>{{ $portfolio->full_name }}</h1><p class="role">{{ $portfolio->workExperiences->first()?->position ?: 'Creative professional' }}@if($portfolio->workExperiences->first()?->company) · {{ $portfolio->workExperiences->first()->company }}@endif</p></div></div><p class="quote">“Small steps<br>create big dreams.”</p></div>
        <section class="about-panel" id="about"><div class="about-copy"><h2>About Me</h2><p>{{ $portfolio->about_me ?: 'I love learning, making thoughtful work, and finding new ways to bring ideas to life.' }}</p></div>@if($portfolio->projects->first()?->image_path)<img class="about-photo" src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($portfolio->projects->first()->image_path) }}" alt="A project from {{ $portfolio->full_name }}">@else<div class="about-photo forest-photo" role="img" aria-label="Forest scenery"></div>@endif</section>
    </section>
    <div class="collage">
        <section class="section skills" id="skills"><h2>My Skills</h2>@if($portfolio->skillEntries->isNotEmpty())<div class="skill-list">@foreach($portfolio->skillEntries as $skill)<span class="skill">{{ $skill->name }} <small>{{ $skill->level }}</small></span>@endforeach</div>@else<p class="empty-state">Skills will appear here when they’re added.</p>@endif</section>
        <section class="section education" id="education"><h2>Education</h2>@if($portfolio->educationEntries->isNotEmpty())<div class="education-list">@foreach($portfolio->educationEntries as $item)<article class="timeline-item"><h3>{{ $item->school }}</h3><div class="meta">{{ $item->degree }}@if($item->field_of_study) · {{ $item->field_of_study }}@endif · {{ $item->start_date?->format('Y') ?? '' }}@if($item->start_date || $item->end_date) – @endif{{ $item->currently_studying ? 'Present' : ($item->end_date?->format('Y') ?? '') }}</div>@if($item->description)<p>{{ $item->description }}</p>@endif</article>@endforeach</div>@else<p class="empty-state">Education details will appear here when they’re added.</p>@endif</section>
        <section class="section projects" id="projects"><h2>My Projects</h2>@if($portfolio->projects->isNotEmpty())<div class="project-grid">@foreach($portfolio->projects as $project)<article class="project">@if($project->image_path)<div class="project-media"><img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($project->image_path) }}" alt="Project image for {{ $project->title }}"></div>@else<div class="project-media project-placeholder" role="img" aria-label="Forest project preview"></div>@endif<div class="project-body"><h3>{{ $project->title }}</h3>@if($project->description)<p>{{ \Illuminate\Support\Str::limit($project->description, 110) }}</p>@endif @if($project->technologies)<div class="tags">{{ implode(' · ', $project->technologies) }}</div>@endif @if($project->project_url || $project->github_url)<div class="project-links">@if($project->project_url)<a href="{{ $project->project_url }}" target="_blank" rel="noopener noreferrer">Visit ↗</a>@endif @if($project->github_url)<a href="{{ $project->github_url }}" target="_blank" rel="noopener noreferrer">GitHub ↗</a>@endif</div>@endif</div></article>@endforeach</div>@else<p class="empty-state">Projects will appear here when they’re added.</p>@endif</section>
        <section class="section experience" id="experience"><h2>Work Experience</h2>@if($portfolio->workExperiences->isNotEmpty())<div class="experience-list">@foreach($portfolio->workExperiences as $item)<article class="timeline-item"><h3>{{ $item->position }}</h3><div class="meta">{{ $item->company }} · {{ $item->start_date?->format('M Y') ?? '' }}@if($item->start_date || $item->end_date) – @endif{{ $item->currently_working ? 'Present' : ($item->end_date?->format('M Y') ?? '') }}</div>@if($item->description)<p>{{ $item->description }}</p>@endif</article>@endforeach</div>@else<p class="empty-state">Work experience will appear here when it’s added.</p>@endif</section>
        <section class="section contact" id="contact"><h2>Connect With Me</h2>@if($portfolio->email || $portfolio->contact_number || $portfolio->address || $portfolio->socialLinks->isNotEmpty())<div class="contact-row">@if($portfolio->email)<a href="mailto:{{ $portfolio->email }}">{{ $portfolio->email }}</a>@endif @if($portfolio->contact_number)<a href="tel:{{ $portfolio->contact_number }}">{{ $portfolio->contact_number }}</a>@endif @if($portfolio->address)<span>{{ $portfolio->address }}</span>@endif</div><div class="social-list">@foreach($portfolio->socialLinks as $link)<a href="{{ $link->url }}" target="_blank" rel="noopener noreferrer">{{ $link->platform }} ↗</a>@endforeach</div>@else<p class="empty-state">Contact details will appear here when they’re added.</p>@endif</section>
    </div>
    <footer class="footer">{{ $portfolio->full_name }} · Made with care</footer>
</div></main>
</body>
</html>
