<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f3f0e4">
    <title>{{ $portfolio->full_name }} · Simple Portfolio</title>
    <style>
        .embedded-preview{width:1200px;min-width:1200px;overflow:hidden;scrollbar-width:none}.embedded-preview::-webkit-scrollbar{display:none}.demo-preview main a{pointer-events:none}
        :root{color-scheme:light;--paper:#f4f1e5;--card:#fbfaf4;--ink:#222d24;--muted:#667365;--moss:#536c50;--line:#d9ddcf;--leaf:#82976b}*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:25px}body{margin:0;background:radial-gradient(ellipse at 2% 10%,#dfe5d2 0,transparent 25%),radial-gradient(ellipse at 100% 78%,#e0e6d5 0,transparent 27%),var(--paper);color:var(--ink);font:15px/1.7 Georgia,"Times New Roman",serif}.toolbar{position:sticky;top:0;z-index:10;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px max(20px,calc((100vw - 1060px)/2));border-bottom:1px solid #dce0d2;background:#f8f7efdF;backdrop-filter:blur(12px);font-family:Segoe UI,Arial,sans-serif}.toolbar a{color:#476148;text-decoration:none;font-size:12px;font-weight:650}.toolbar .preview-label{color:#748071;font-size:12px}.toolbar button{border:0;border-radius:5px;padding:8px 12px;background:#4d674d;color:#fff;font:inherit;font-size:11px;font-weight:700;cursor:pointer}.template-notice{max-width:990px;margin:12px auto 0;padding:10px 13px;border:1px solid #b4c7a4;border-radius:8px;background:#edf4e7;color:#37583c;font:12px Segoe UI,Arial,sans-serif}
        .wrap{position:relative;max-width:1020px;margin:45px auto 65px;padding:0 28px}.wrap:before{position:absolute;z-index:-1;top:3px;right:0;width:75px;height:100px;background:url('{{ asset('images/login-foliage.svg') }}') center/contain no-repeat;content:"";opacity:.24;transform:rotate(14deg)}.intro{display:grid;grid-template-columns:minmax(0,1fr) 130px;align-items:center;gap:32px;padding:4px 0 29px;border-bottom:1px solid var(--line)}.kicker{margin:0;color:#58715a;font:700 10px/1.5 Segoe UI,Arial,sans-serif;letter-spacing:.17em;text-transform:uppercase}.intro h1{margin:9px 0 7px;font-size:clamp(39px,6.5vw,68px);font-weight:500;line-height:1.03;letter-spacing:-.045em}.intro p{max-width:680px;margin:0;color:#5e685c;font-size:15px}.portrait{width:122px;height:122px;object-fit:cover;border:1px solid #d0d7c4;border-radius:50%;filter:saturate(.82)}.initials{display:grid;place-items:center;background:#e2e6d8;color:#446047;font:500 42px Segoe UI,Arial,sans-serif}.contact-cta{display:inline-flex;margin-top:14px;padding:7px 12px;border:1px solid #789071;border-radius:999px;color:#405b45;text-decoration:none;font:650 11px Segoe UI,Arial,sans-serif}
        .content{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(220px,.75fr);gap:50px;margin-top:28px}.section{margin-bottom:29px;scroll-margin-top:22px}.section h2{display:flex;align-items:center;gap:8px;margin:0 0 12px;color:#536c50;font:700 10px/1.5 Segoe UI,Arial,sans-serif;letter-spacing:.15em;text-transform:uppercase}.section h2:before{width:15px;height:1px;background:#849878;content:""}.about-copy{max-width:690px;color:#4e574c;font-size:15px}.item{padding:0 0 12px;margin-bottom:12px;border-bottom:1px solid #dfe2d8}.item:last-child{padding:0;margin:0;border:0}.item h3{margin:0;color:#2c362d;font-size:17px;font-weight:500;letter-spacing:-.01em}.meta{color:#718071;font:12px/1.6 Segoe UI,Arial,sans-serif}.item p{margin:5px 0 0;color:#576154;font-size:14px}.skill-list{display:grid}.skill{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid #e0e2d9;color:#39463a;font:13px Segoe UI,Arial,sans-serif}.skill small{color:#778273;font-size:11px}.contact{display:grid;gap:6px;color:#536052;font:12px/1.6 Segoe UI,Arial,sans-serif;overflow-wrap:anywhere}.contact a,.social-list a,.project-links a{color:#496649;text-decoration:none}.contact a:hover,.social-list a:hover,.project-links a:hover{text-decoration:underline;text-underline-offset:3px}.social-list{display:grid;gap:5px;margin-top:10px;font:12px Segoe UI,Arial,sans-serif}.project{padding:0 0 13px;margin-bottom:13px;border-bottom:1px solid #dfe2d8}.project:last-child{margin:0;padding:0;border:0}.project h3{margin:0;font-size:18px;font-weight:500}.project p{margin:4px 0 0;color:#576154}.project-media{height:112px;margin:9px 0 5px;overflow:hidden;border:1px solid #dce0d2;border-radius:4px;background:linear-gradient(145deg,#82976b,#d9dfcc)}.project-media img{width:100%;height:100%;object-fit:cover}.tags{margin-top:6px;color:#768170;font:11px Segoe UI,Arial,sans-serif}.project-links{display:flex;gap:11px;margin-top:7px;font:11px Segoe UI,Arial,sans-serif}.footer{padding:15px 0;border-top:1px solid var(--line);color:#7d867a;font:11px Segoe UI,Arial,sans-serif}
        body{background:linear-gradient(rgba(8,19,12,.62),rgba(8,19,12,.68)),url('https://images.unsplash.com/photo-1546835196-5fe79a546d7c?auto=format&fit=crop&w=2000&q=78') center/cover fixed;color:var(--ink)}.wrap{padding:28px;background:rgba(250,249,242,.96);border:1px solid #ffffffb5;border-radius:16px;box-shadow:0 18px 55px #0005;backdrop-filter:blur(5px)}
        @media(max-width:700px){.wrap{margin:30px auto 48px;padding:20px 19px}.intro{grid-template-columns:minmax(0,1fr) 78px;gap:12px;padding-bottom:20px}.intro h1{font-size:clamp(36px,10vw,54px)}.intro p{font-size:13px}.portrait{width:76px;height:76px}.content{grid-template-columns:1fr;gap:0;margin-top:22px}.section{margin-bottom:24px}.toolbar{padding:9px 12px}.toolbar .preview-label{display:none}.template-notice{margin-inline:12px}}
        @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
    </style>
    <link rel="stylesheet" href="{{ asset('css/everleaf-cursors.css') }}">
    <link rel="stylesheet" href="{{ asset('css/everleaf-theme-toggle.css') }}">
    <script src="{{ asset('js/everleaf-theme-toggle.js') }}" defer></script>
</head>
<body class="site-template-minimal {{ ($embedded ?? false) ? 'embedded-preview' : '' }} {{ ($demo ?? false) ? 'demo-preview' : '' }}">
@include('portfolios.templates._toolbar')
<main class="wrap">
    <section class="intro" id="home"><div><p class="kicker">Portfolio · Simple style</p><h1>{{ $portfolio->full_name }}</h1><p>{{ $portfolio->about_me ?: 'A little about me and the work I care about.' }}</p>@if($portfolio->email)<a class="contact-cta" href="mailto:{{ $portfolio->email }}">Get in touch ↗</a>@endif</div>
        @if($portfolio->profile_photo_path)<img class="portrait" src="{{ asset('storage/'.$portfolio->profile_photo_path) }}" alt="Profile photo of {{ $portfolio->full_name }}">@else<div class="portrait initials" aria-hidden="true">{{ strtoupper(substr($portfolio->full_name, 0, 1)) }}</div>@endif
    </section>
    <div class="content">
        <div>
            @if($portfolio->about_me)<section class="section" id="about"><h2>About</h2><div class="about-copy">{{ $portfolio->about_me }}</div></section>@endif
            @if($portfolio->projects->isNotEmpty())<section class="section" id="projects"><h2>Selected Projects</h2>@foreach($portfolio->projects as $project)<article class="project"><h3>{{ $project->title }}</h3>@if($project->image_path)<div class="project-media"><img src="{{ asset('storage/'.$project->image_path) }}" alt="Project image for {{ $project->title }}"></div>@endif @if($project->description)<p>{{ $project->description }}</p>@endif @if($project->technologies)<div class="tags">{{ implode(' · ', $project->technologies) }}</div>@endif @if($project->project_url || $project->github_url)<div class="project-links">@if($project->project_url)<a href="{{ $project->project_url }}" target="_blank" rel="noopener noreferrer">View project ↗</a>@endif @if($project->github_url)<a href="{{ $project->github_url }}" target="_blank" rel="noopener noreferrer">Source ↗</a>@endif</div>@endif</article>@endforeach</section>@endif
            @if($portfolio->workExperiences->isNotEmpty())<section class="section" id="experience"><h2>Experience</h2>@foreach($portfolio->workExperiences as $item)<article class="item"><h3>{{ $item->position }}</h3><div class="meta">{{ $item->company }} · {{ $item->start_date?->format('M Y') ?? '' }}@if($item->start_date || $item->end_date) – @endif{{ $item->currently_working ? 'Present' : ($item->end_date?->format('M Y') ?? '') }}</div>@if($item->description)<p>{{ $item->description }}</p>@endif</article>@endforeach</section>@endif
        </div>
        <aside>
            @if($portfolio->educationEntries->isNotEmpty())<section class="section" id="education"><h2>Education</h2>@foreach($portfolio->educationEntries as $item)<article class="item"><h3>{{ $item->degree }}</h3><div class="meta">{{ $item->school }}@if($item->field_of_study) · {{ $item->field_of_study }}@endif · {{ $item->start_date?->format('Y') ?? '' }}@if($item->start_date || $item->end_date) – @endif{{ $item->currently_studying ? 'Present' : ($item->end_date?->format('Y') ?? '') }}</div>@if($item->description)<p>{{ $item->description }}</p>@endif</article>@endforeach</section>@endif
            @if($portfolio->skillEntries->isNotEmpty())<section class="section" id="skills"><h2>Skills</h2><div class="skill-list">@foreach($portfolio->skillEntries as $skill)<div class="skill"><span>{{ $skill->name }}</span><small>{{ $skill->level }}</small></div>@endforeach</div></section>@endif
            @if($portfolio->email || $portfolio->contact_number || $portfolio->address || $portfolio->socialLinks->isNotEmpty())<section class="section" id="contact"><h2>Contact</h2><div class="contact">@if($portfolio->email)<a href="mailto:{{ $portfolio->email }}">{{ $portfolio->email }}</a>@endif @if($portfolio->contact_number)<a href="tel:{{ $portfolio->contact_number }}">{{ $portfolio->contact_number }}</a>@endif @if($portfolio->address)<span>{{ $portfolio->address }}</span>@endif</div><div class="social-list">@foreach($portfolio->socialLinks as $link)<a href="{{ $link->url }}" target="_blank" rel="noopener noreferrer">{{ $link->platform }} ↗</a>@endforeach</div></section>@endif
        </aside>
    </div>
    <footer class="footer">{{ $portfolio->full_name }} · Simple Portfolio</footer>
</main>
</body>
</html>
