<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#102018"><title>{{ $portfolio->full_name }} · Modern Portfolio</title>
    <style>
        .embedded-preview{width:1200px;min-width:1200px;overflow:hidden;scrollbar-width:none}.embedded-preview::-webkit-scrollbar{display:none}.demo-preview main a{pointer-events:none}
        :root{color-scheme:dark;--bg:#07150f;--panel:#102219;--panel2:#13291d;--line:#dce8c52b;--ink:#f1f0df;--muted:#b9c7b4;--leaf:#cadb9d;--accent:#8da96c}*{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:22px}body{margin:0;background:#09160f url('{{ asset('images/forest-hero.svg') }}') center/cover fixed;color:var(--ink);font:15px/1.6 Inter,"Segoe UI",Arial,sans-serif}body:before{position:fixed;z-index:-1;inset:0;background:#06120edc;content:""}a{color:inherit}.toolbar{position:sticky;top:0;z-index:10;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px max(18px,calc((100vw - 1320px)/2));border-bottom:1px solid var(--line);background:#0b1a12eF;backdrop-filter:blur(14px)}.toolbar a{color:var(--leaf);text-decoration:none;font-size:12px;font-weight:650}.toolbar .preview-label{color:#c5d0be;font-size:12px}.toolbar form{margin:0}.toolbar button{border:1px solid #d7e7b768;border-radius:999px;padding:8px 13px;background:#526d3e;color:#fffbe8;font:inherit;font-size:11px;font-weight:750;cursor:pointer}.template-notice{max-width:1250px;margin:12px auto 0;padding:10px 14px;border:1px solid #b7d68a78;border-radius:10px;background:#223b26;color:#eef4d5;font-size:12px}
        .layout{display:grid;grid-template-columns:214px minmax(0,1fr);gap:20px;max-width:1360px;margin:24px auto;padding:0 20px}.sidebar{position:sticky;top:82px;display:flex;height:calc(100vh - 106px);min-height:540px;flex-direction:column;padding:16px 12px;border:1px solid var(--line);border-radius:16px;background:linear-gradient(180deg,#10241beF,#0a1a12ef);box-shadow:0 20px 55px #0006}.identity{display:grid;justify-items:center;padding:6px 5px 15px;text-align:center}.portrait{width:76px;height:76px;object-fit:cover;border:2px solid #cbdca180;border-radius:50%;background:#273e2c}.initials{display:grid;place-items:center;background:linear-gradient(145deg,#829b62,#2f4831);color:#fffbe6;font:700 29px Georgia,serif}.identity strong{margin-top:8px;font:600 15px Georgia,serif}.identity small{margin-top:2px;color:#b4c2af;font-size:9px}.side-nav{display:grid;gap:4px;margin-top:8px}.side-nav a{display:flex;align-items:center;gap:9px;padding:8px 9px;border:1px solid transparent;border-radius:8px;color:#d2ddcc;text-decoration:none;font-size:11px}.side-nav a:hover,.side-nav a:first-child{border-color:#d4e7b624;background:#d4e7b617;color:#f3f2df}.side-icon{width:14px;color:var(--leaf);text-align:center}.side-contact{margin-top:auto;padding:12px 9px;border:1px solid var(--line);border-radius:10px;background:#e7eddc09}.side-contact strong{display:block;margin-bottom:3px;font:600 12px Georgia,serif}.side-contact p{margin:0 0 7px;color:var(--muted);font-size:9px}.side-contact a{display:inline-flex;gap:7px;margin:3px 8px 0 0;color:#d5e5b3;text-decoration:none;font-size:10px}
        .portfolio{min-width:0}.hero{position:relative;isolation:isolate;display:flex;min-height:200px;align-items:center;justify-content:space-between;gap:25px;overflow:hidden;padding:27px clamp(20px,4vw,40px);border:1px solid #dce8c541;border-radius:15px;background:linear-gradient(90deg,#08160feF,#10251aa8 72%,#0a190fd9),url('{{ asset('images/forest-hero.svg') }}') center 52%/cover;box-shadow:0 20px 55px #0005}.hero:after{position:absolute;z-index:-1;right:4%;top:-100px;width:250px;height:250px;border:1px solid #d8e8bc39;border-radius:50%;box-shadow:0 0 0 22px #d8e8bc09,0 0 0 48px #d8e8bc08;content:""}.hero-copy{position:relative;z-index:1;max-width:740px}.eyebrow{margin:0;color:#cadc9c;font-size:9px;font-weight:800;letter-spacing:.16em;text-transform:uppercase}.hero h1{margin:5px 0;font:600 clamp(27px,4vw,42px)/1.12 Georgia,"Times New Roman",serif;letter-spacing:-.03em}.hero p{max-width:670px;margin:0;color:#d0d9c8;font-size:11px}.hero a{display:inline-flex;margin-top:10px;border:1px solid #d8e8b856;border-radius:999px;padding:6px 11px;background:#314b2b;color:#f5f2df;text-decoration:none;font-size:10px;font-weight:700}.hero-photo{width:72px;height:72px;flex:none;border:2px solid #d8e7b878;border-radius:50%;object-fit:cover;background:#4d6745;box-shadow:0 0 0 5px #e1eccb18}.hero-initials{display:grid;place-items:center;color:#f7f4df;font:700 27px Georgia,serif}
        .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:12px 0}.stat{padding:10px 13px;border:1px solid var(--line);border-radius:10px;background:linear-gradient(120deg,#11251bdc,#0d1e15eb)}.stat strong{display:block;color:#edf1dc;font:600 20px Georgia,serif}.stat span{color:#bac8b3;font-size:9px}
        .content-grid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.card{min-width:0;padding:14px;border:1px solid var(--line);border-radius:12px;background:linear-gradient(145deg,#13281dda,#0c1d14ec);box-shadow:0 10px 28px #0003;scroll-margin-top:20px}.card h2{display:flex;align-items:center;gap:7px;margin:0 0 9px;color:#f0f0de;font:600 15px Georgia,"Times New Roman",serif}.card h2:before{width:3px;height:15px;border-radius:3px;background:#9eb876;content:""}.card p{margin:0;color:#c3cebd;font-size:10px;line-height:1.55}.about-card{grid-column:1}.project-card{grid-column:2;grid-row:1/span 2}.skills-card{grid-column:1}.experience-card{grid-column:1/-1}.education-card{grid-column:1/-1}.contact-card{grid-column:1/-1}.project-list{display:grid;gap:7px}.project{display:grid;grid-template-columns:55px minmax(0,1fr);align-items:center;gap:9px;padding:7px;border:1px solid #dbe8c51d;border-radius:8px;background:#09180f99}.project-image{display:grid;width:55px;height:48px;place-items:center;overflow:hidden;border:1px solid #dbe8c53a;border-radius:6px;background:linear-gradient(145deg,#536f44,#132819)}.project-image img{width:100%;height:100%;object-fit:cover}.project h3{margin:0;color:#f0f0df;font-size:10px}.project p{margin-top:2px;font-size:8px}.project-meta{margin-top:3px;color:#b4c5a8;font-size:8px}.project-links{display:flex;gap:10px;margin-top:4px}.project-links a,.social-list a{color:#d2e3a9;text-decoration:none;font-size:8px}.chips{display:flex;flex-wrap:wrap;gap:5px}.chip{padding:4px 7px;border:1px solid #d8e8c528;border-radius:999px;background:#263b2a;color:#e1e9d4;font-size:9px}.chip small{color:#aebb9e}.timeline{display:grid;gap:9px}.timeline-item{padding-left:10px;border-left:2px solid #78935c}.timeline-item h3{margin:0;color:#eef0df;font-size:10px}.timeline-meta{margin:2px 0;color:#afc1a7;font-size:8px}.timeline-item p{font-size:9px}.social-list{display:flex;flex-wrap:wrap;gap:7px}.social-list a{display:inline-block;padding:5px 8px;border:1px solid var(--line);border-radius:7px;background:#162a1d}.contact-details{display:flex;flex-wrap:wrap;gap:7px 14px;margin-bottom:8px;color:#c7d1c0;font-size:9px;overflow-wrap:anywhere}.contact-details a{color:#d6e5b5;text-decoration:none}.footer{padding:17px 0;color:#aab9a3;text-align:center;font-size:9px}
        @media(max-width:800px){.layout{grid-template-columns:1fr;gap:12px;margin:14px auto;padding:0 13px}.sidebar{position:relative;top:0;height:auto;min-height:0;display:grid;grid-template-columns:auto 1fr;align-items:center;gap:8px;padding:10px}.identity{display:flex;justify-items:initial;gap:8px;padding:0;text-align:left}.portrait{width:39px;height:39px}.identity strong{margin:0;font-size:11px}.identity small{display:none}.side-nav{display:flex;justify-content:flex-end;gap:3px;margin:0;overflow:auto}.side-nav a{gap:4px;padding:6px;font-size:9px}.side-icon{width:auto}.side-contact{display:none}.hero{min-height:170px}.hero-photo{width:60px;height:60px}.card{padding:12px}}
        @media(max-width:520px){.toolbar{padding:9px 12px}.toolbar .preview-label{display:none}.layout{margin:10px auto}.sidebar{display:block}.identity{justify-content:center;padding-bottom:8px;border-bottom:1px solid var(--line)}.side-nav{justify-content:space-between;padding-top:7px}.side-nav a{display:grid;justify-items:center;gap:2px;min-width:43px;padding:4px 2px;font-size:8px}.side-icon{font-size:12px}.hero{min-height:180px;align-items:flex-start;padding:19px 15px}.hero-photo{width:44px;height:44px}.hero h1{font-size:26px}.hero p{font-size:10px}.stats{gap:5px}.stat{padding:8px}.stat strong{font-size:16px}.stat span{font-size:8px}.content-grid{grid-template-columns:1fr}.card,.about-card,.project-card,.skills-card,.experience-card,.education-card,.contact-card{grid-column:1;grid-row:auto}.project-card{grid-row:auto}.template-notice{margin-inline:10px}}
        .side-nav a:first-child{border-color:transparent;background:transparent;color:#d2ddcc}.side-nav a[aria-current="location"]{border-color:#d4e7b624;background:#d4e7b617;color:#f3f2df}.empty-state{padding:10px;border:1px dashed #dbe8c536;border-radius:8px;background:#09180f55;color:#bac8b3;font-size:10px}.card:target{border-color:#c9dc9a9c;box-shadow:0 0 0 2px #c9dc9a18,0 12px 30px #0004}
        body{background:linear-gradient(rgba(5,17,10,.66),rgba(5,17,10,.78)),url('https://images.unsplash.com/photo-1546835196-5fe79a546d7c?auto=format&fit=crop&w=2000&q=78') center/cover fixed}body:before{display:none}.hero{background:linear-gradient(90deg,rgba(8,22,14,.88),rgba(16,37,26,.54) 72%,rgba(10,25,15,.76)),url('https://images.unsplash.com/photo-1546835196-5fe79a546d7c?auto=format&fit=crop&w=1400&q=76') center 52%/cover}
        @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
    </style>
    <link rel="stylesheet" href="{{ asset('css/everleaf-cursors.css') }}">
    <link rel="stylesheet" href="{{ asset('css/everleaf-theme-toggle.css') }}">
    <link rel="stylesheet" href="{{ asset('css/portfolio-navigation.css') }}">
    <script src="{{ asset('js/everleaf-theme-toggle.js') }}" defer></script>
    <script src="{{ asset('js/portfolio-section-navigation.js') }}" defer></script>
</head>
<body class="site-template-modern {{ ($embedded ?? false) ? 'embedded-preview' : '' }} {{ ($demo ?? false) ? 'demo-preview' : '' }}">
@include('portfolios.templates._toolbar')
<div class="layout">
    <aside class="sidebar">
        <div class="identity">
            @if($portfolio->profile_photo_path)<img class="portrait" src="{{ asset('storage/'.$portfolio->profile_photo_path) }}" alt="">@else<div class="portrait initials" aria-hidden="true">{{ strtoupper(substr($portfolio->full_name, 0, 1)) }}</div>@endif
            <div><strong>{{ $portfolio->full_name }}</strong><small>{{ $portfolio->about_me ? \Illuminate\Support\Str::limit($portfolio->about_me, 46) : 'Portfolio · '.$templateLabel.' style' }}</small></div>
        </div>
        <nav class="side-nav portfolio-section-nav" aria-label="Portfolio sections"><a href="#home" aria-current="location"><span class="side-icon">⌂</span>Home</a><a href="#about"><span class="side-icon">◉</span>About</a><a href="#skills"><span class="side-icon">✳</span>Skills</a><a href="#projects"><span class="side-icon">▧</span>Projects</a>@if($portfolio->educationEntries->isNotEmpty())<a href="#education"><span class="side-icon">▤</span>Education</a>@endif<a href="#experience"><span class="side-icon">◷</span>Experience</a><a href="#contact"><span class="side-icon">✉</span>Contact</a></nav>
        <div class="side-contact"><strong>Let’s Connect</strong><p>Feel free to reach out.</p>@if($portfolio->email)<a href="mailto:{{ $portfolio->email }}">✉ Email</a>@endif @foreach($portfolio->socialLinks as $link)<a href="{{ $link->url }}" target="_blank" rel="noopener noreferrer">{{ $link->platform }} ↗</a>@endforeach</div>
    </aside>
    <main class="portfolio">
        <section class="hero" id="home"><div class="hero-copy"><p class="eyebrow">Portfolio · Modern style</p><h1>Hello, I’m {{ $portfolio->full_name }}</h1><p>{{ $portfolio->about_me ?: 'I build thoughtful digital experiences and meaningful work.' }}</p>@if($portfolio->email)<a href="mailto:{{ $portfolio->email }}">Let’s connect ↗</a>@endif</div>
            @if($portfolio->profile_photo_path)<img class="hero-photo" src="{{ asset('storage/'.$portfolio->profile_photo_path) }}" alt="Profile photo of {{ $portfolio->full_name }}">@else<div class="hero-photo hero-initials" aria-hidden="true">{{ strtoupper(substr($portfolio->full_name, 0, 1)) }}</div>@endif
        </section>
        <section class="stats" aria-label="Portfolio highlights"><div class="stat"><strong>{{ $portfolio->projects->count() }}+</strong><span>Projects</span></div><div class="stat"><strong>{{ $portfolio->skillEntries->count() }}+</strong><span>Skills</span></div><div class="stat"><strong>{{ $portfolio->workExperiences->count() }}+</strong><span>Experience roles</span></div></section>
        <div class="content-grid">
            <section class="card about-card" id="about"><h2>About Me</h2><p>{{ $portfolio->about_me ?: 'Welcome to my portfolio. Explore my work, skills, and experience below.' }}</p></section>
            <section class="card project-card" id="projects"><h2>Featured Projects</h2>@if($portfolio->projects->isNotEmpty())<div class="project-list">@foreach($portfolio->projects as $project)<article class="project"><div class="project-image">@if($project->image_path)<img src="{{ asset('storage/'.$project->image_path) }}" alt="">@else<span aria-hidden="true">❧</span>@endif</div><div><h3>{{ $project->title }}</h3>@if($project->description)<p>{{ \Illuminate\Support\Str::limit($project->description, 100) }}</p>@endif @if($project->technologies)<div class="project-meta">{{ implode(' · ', $project->technologies) }}</div>@endif @if($project->project_url || $project->github_url)<div class="project-links">@if($project->project_url)<a href="{{ $project->project_url }}" target="_blank" rel="noopener noreferrer">View project ↗</a>@endif @if($project->github_url)<a href="{{ $project->github_url }}" target="_blank" rel="noopener noreferrer">GitHub ↗</a>@endif</div>@endif</div></article>@endforeach</div>@else<p class="empty-state">Projects will appear here when they’re added.</p>@endif</section>
            <section class="card skills-card" id="skills"><h2>Skills</h2>@if($portfolio->skillEntries->isNotEmpty())<div class="chips">@foreach($portfolio->skillEntries as $skill)<span class="chip">{{ $skill->name }} <small>· {{ $skill->level }}</small></span>@endforeach</div>@else<p class="empty-state">Skills will appear here when they’re added.</p>@endif</section>
            @if($portfolio->educationEntries->isNotEmpty())<section class="card education-card" id="education"><h2>Education</h2><div class="timeline">@foreach($portfolio->educationEntries as $item)<article class="timeline-item"><h3>{{ $item->degree }}@if($item->field_of_study) · {{ $item->field_of_study }}@endif</h3><div class="timeline-meta">{{ $item->school }} · {{ $item->start_date?->format('Y') ?? '' }}@if($item->start_date || $item->end_date) – @endif{{ $item->currently_studying ? 'Present' : ($item->end_date?->format('Y') ?? '') }}</div>@if($item->description)<p>{{ $item->description }}</p>@endif</article>@endforeach</div></section>@endif
            <section class="card experience-card" id="experience"><h2>Experience</h2>@if($portfolio->workExperiences->isNotEmpty())<div class="timeline">@foreach($portfolio->workExperiences as $item)<article class="timeline-item"><h3>{{ $item->position }} · {{ $item->company }}</h3><div class="timeline-meta">{{ $item->start_date?->format('M Y') ?? '' }}@if($item->start_date || $item->end_date) – @endif{{ $item->currently_working ? 'Present' : ($item->end_date?->format('M Y') ?? '') }}</div>@if($item->description)<p>{{ $item->description }}</p>@endif</article>@endforeach</div>@else<p class="empty-state">Work experience will appear here when it’s added.</p>@endif</section>
            <section class="card contact-card" id="contact"><h2>Contact</h2>@if($portfolio->email || $portfolio->contact_number || $portfolio->address || $portfolio->socialLinks->isNotEmpty())<div class="contact-details">@if($portfolio->email)<a href="mailto:{{ $portfolio->email }}">{{ $portfolio->email }}</a>@endif @if($portfolio->contact_number)<a href="tel:{{ $portfolio->contact_number }}">{{ $portfolio->contact_number }}</a>@endif @if($portfolio->address)<span>{{ $portfolio->address }}</span>@endif</div><div class="social-list">@foreach($portfolio->socialLinks as $link)<a href="{{ $link->url }}" target="_blank" rel="noopener noreferrer">{{ $link->platform }} ↗</a>@endforeach</div>@else<p class="empty-state">Contact details will appear here when they’re added.</p>@endif</section>
        </div>
        <footer class="footer">{{ $portfolio->full_name }} · {{ $templateLabel }} Portfolio</footer>
    </main>
</div>
</body>
</html>
